apiVersion: v1
kind: Service
metadata:
  name: connect40
  labels:
    app.kubernetes.io/name: connect40
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: connect40
  ports:
    - name: http
      port: 80
      targetPort: http
